### PR TITLE
add feature to support #39, use @javax.persistence.Transient

### PR DESCRIPTION
**Pull request by CorvusYe**

### CODE REVIEW

**Review by wey-gu — APPROVED** [review]
❤

**Comment by CorvusYe** [comment]
@wey-gu 
What do you think of the beta release based on the current version.

**Comment by wey-gu** [comment]
> @wey-gu What do you think of releasing a beta version based on current.

I am good with a beta release :)

**Comment by CorvusYe** [comment]
> I am good with a beta release :)

Has the release process we metioned earlier been determined ? 
If not, this version would be released directly, ok ?

**Comment by wey-gu** [comment]
> > I am good with a beta release :)
> 
> Has the release process we metioned earlier been determined ? If not, this version would be released directly, ok ?

Yes, please release directly now :)

**Pull request merged**
