### PR TITLE
Feat: add insertEdgeBatch function #234

### PR DESCRIPTION
**Pull request by shbone**
According to https://github.com/nebula-contrib/ngbatis/issues/234#issue-1916633019   #234 
add insertEdgeBatch function
include:
- test module
- reformat `src/main/resources/NebulaDaoBasic.xml` 
cc @CorvusYe Thank you!

### CODE REVIEW

**Review by CorvusYe — CHANGES_REQUESTED** [review]
It might be better to move NgTriplet to the models of the main project, which is at the same level as NgPath.

**Comment by shbone** [comment]
> Reference

Thank you!
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (checkstyle) on project ngbatis-demo: You have 60 Checkstyle violations. -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Process completed with exit code 1.
```
 And I want to know how to set `checkstyle` when I use IDEA. Apparently, It have some violation when use `maven -B install `command.  I want to set the `xxx.xml` code style configuraion file to correct these warning. @CorvusYe

**Comment by shbone** [comment]
> > Reference
> 
> Thank you!
> 
> ```
> Error:  Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (checkstyle) on project ngbatis-demo: You have 60 Checkstyle violations. -> [Help 1]
> Error:  
> Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
> Error:  Re-run Maven using the -X switch to enable full debug logging.
> Error:  
> Error:  For more information about the errors and possible solutions, please read the following articles:
> Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> Error: Process completed with exit code 1.
> ```
> 
> And I want to know how to set `checkstyle` when I use IDEA. Apparently, It have some violation when use `maven -B install `command. I want to set the `xxx.xml` code style configuraion file to correct these warning. @CorvusYe

I think `nebula_java_style_checks.xml`is the codestyle configuration file. Yes or No?

**Review by CorvusYe — APPROVED** [review]

**Comment by CorvusYe** [comment]
Great !
If you don't mind, could you add some author information to the pom.

**Comment by shbone** [comment]
> Great ! If you don't mind, could you add some author information to the pom.

That sounds great! I will add my personal information next pr! Thank you!
And your review is so quickly!

**Review by wey-gu — APPROVED** [review]

**Review by CorvusYe — APPROVED** [review]

**Pull request merged**
