### PR TITLE
add pr ci

### PR DESCRIPTION
**Pull request by Nicole00**
please do not merge until files have been formatted.

### CODE REVIEW

**Comment by Nicole00** [comment]
@CorvusYe

**Review by CorvusYe — APPROVED** [review]

**Review by wey-gu — APPROVED** [review]
👍🏻

**Comment by Nicole00** [comment]
force merge

**Comment by CorvusYe** [comment]
Maybe we need to modify the style again_ checks. XML to fit Google style.
It was Sun style.

**Pull request merged**
