### PR TITLE
edit file name

### PR DESCRIPTION
**Pull request by shbone**
edit file name ,add 'e' to the filename @wey-gu

### CODE REVIEW

**Review by wey-gu — APPROVED** [review]

**Review by CorvusYe — APPROVED** [review]

**Review by liuxiaocs7 — APPROVED** [review]
LGTM for file name change, but this file doesn’t seem to be working, is it possible to consider removing it?

**Comment by wey-gu** [comment]
> LGTM for file name change, but this file doesn’t seem to be working, is it possible to consider removing it?

We could create further tasks in Oct. to further improve this as Hacktoberfest tasks!

**Comment by CorvusYe** [comment]
> LGTM for file name change, but this file doesn’t seem to be working, is it possible to consider removing it?

I remember that this file does not work in actions, but can be configured to assist in the IDEA reminder, is that so？@Nicole00

**Comment by Nicole00** [comment]
> > LGTM for file name change, but this file doesn’t seem to be working, is it possible to consider removing it?
> 
> I remember that this file does not work in actions, but can be configured to assist in the IDEA reminder, is that so？@Nicole00

Yeah,  in actions the compile does not use this file but use `nebula_java_style_checks.xml` in the maven plugin config. https://github.com/nebula-contrib/ngbatis/blob/fbeb601f0fe30554bc605d7bfd5da962acf32aab/pom.xml#L295

If we want to keep the java code style the same with `nebula_java_style_checks.xml`, we should config the `google-checkstyle.xml` in local IDEA reminder, because there are a little differences between them.
I sugget to remove the `google-checkstyle.xml` to keep one style for the code.

**Pull request merged**
