### PR TITLE
fix: remove unnecessary reflections in transformDateTime

### PR DESCRIPTION
**Pull request by CorvusYe**
Remove unnecessary reflections in transformDateTime, and prevents errors in the millisecond bit in jdk17.
Make the same code applicable to both jdk8 and jdk17 versions, reducing maintenance costs.

### CODE REVIEW

**Review by wey-gu — APPROVED** [review]

**Comment by wey-gu** [comment]
All actions passed.

**Comment by CorvusYe** [comment]
Snapshot always works, but release doesn't. I don't know what more checks

**Comment by wey-gu** [comment]
Shall we bring the skip of doc back first to enable proper release publishments?

**Comment by wey-gu** [comment]
give a 1.2.0 release and see what happens next to exclude the suspicion of naming?

**Pull request merged**
