### PR TITLE
fix #73 [selectById] use id value embedding instead of cypher parameter

### LINKED ISSUE #73: 默认的selectById()查询异常Scan vertices or edges need to specify a limit number, or limit number can not push down.
- 执行默认的selectById()会报异常

image
image

- tag建立索引，修改xml中查询语句指定tag，可正常得出结果
`match (n:organization) where id(n) == $id return n`

- 不建立索引，xml中查询语句指定点的vid同样能查出结果
`match (n) where id(n) == '00005' return n`

请问这有更好的解决方式吗

### PR DESCRIPTION
**Pull request by zb139407**

### CODE REVIEW

**Comment by zb139407** [comment]
fix #73 [selectById] use id value embedding instead of cypher parameter

**Review by CorvusYe — APPROVED** [review]
不介意的话，在pom.xml大概20行的位置添一下作者信息哈~

**Comment by wey-gu** [comment]
Thanks @zb139407 !

BTW, @czpmango helped created this https://github.com/vesoft-inc/nebula/pull/4798 but it looks like cannot catch up with the 3.3.0 release, thus we'll need this non-cypher parameter approach for quite a while.

**Comment by CorvusYe** [comment]
> Thanks @zb139407 !
> 
> BTW, @czpmango helped created this [vesoft-inc/nebula#4798](https://github.com/vesoft-inc/nebula/pull/4798) but it looks like cannot catch up with the 3.3.0 release, thus we'll need this non-cypher parameter approach for quite a while.

@wey-gu 
Maybe we need to consider releasing a stable version of 1.1.0 as soon as possible.

**Comment by zb139407** [comment]
要怎么加作者信息，是关闭当前pr，重新提交吗 @CorvusYe

**Comment by wey-gu** [comment]
> 要怎么加作者信息，是关闭当前pr，重新提交吗 @CorvusYe

当前 pr 绑定了您的 fork 的 master 分支，您把 pom.xml 修改之后直接推到 zb139407:master 就可以反映到这个pr 上了，不用关闭 pr

**Comment by CorvusYe** [comment]
> 要怎么加作者信息，是关闭当前pr，重新提交吗 @CorvusYe

先不关闭，修改一下 pom.xml 再提交一次，提交好了再关闭~

**Review by wey-gu — APPROVED** [review]

**Review by CorvusYe — APPROVED** [review]

**Pull request merged**
