### PR TITLE
feat #103 #118 support. provide default data structure for edge \ vertex \ path \ sub-graph, and their result handler.

### PR DESCRIPTION
**Pull request by CorvusYe**
- feat: provide default data structure for edge \ vertex \ path \ sub-graph, and their result handler. #103 #118
  for example: 
  ```java
  List<NgSubgraph<String>> selectSubgraph();
  ```
  ```xml
  <select id="selectSubgraph" resultType="org.nebula.contrib.ngbatis.models.data.NgSubgraph">
      GET SUBGRAPH WITH PROP 3 STEPS FROM "startVid"
      BOTH like
      YIELD VERTICES AS nodes, EDGES AS relationships
  </select>
  ```
  > ##  **alias must be nodes and relationship.**

- feat: NebulaDaoBasic shortest path support. #118

    ```java
    List<NgPath<String>> ngPaths = dao.shortestPath("startId", "endId");
    ```

### CODE REVIEW

**Comment by wey-gu** [comment]
Wow! 👍
BTW the build seems to fail in ci?

**Comment by CorvusYe** [comment]
> Wow! 👍 BTW the build seems to fail in ci?

The test depends on unpublished version.
CI flow may install ngbatis first and then build ngbatis-demo.

**Comment by CorvusYe** [comment]
But we build ngbatis-demo directly now.
This results in that the test code and the new feature code cannot be committed together.

**Review by wey-gu — APPROVED** [review]

**Comment by wey-gu** [comment]
> But we build ngbatis-demo directly now. This results in that the test code and the new feature code cannot be committed together.

OK, maybe we could revisit this in the future :)

**Comment by CorvusYe** [comment]
> > But we build ngbatis-demo directly now. This results in that the test code and the new feature code cannot be committed together.
> 
> OK, maybe we could revisit this in the future :)

Yes, I have fixed the version time difference by this commit. `ngbatis-demo` depends on 'ngbatis' from local maven repository when building. https://github.com/nebula-contrib/ngbatis/pull/119/commits/31cac59371b535e5f339b7743d03b4b4cb16991c

**Comment by wey-gu** [comment]
> > > But we build ngbatis-demo directly now. This results in that the test code and the new feature code cannot be committed together.
> > 
> > 
> > OK, maybe we could revisit this in the future :)
> 
> Yes, I have fixed the version time difference by this commit. `ngbatis-demo` depends on 'ngbatis' from local maven repository when building. [31cac59](https://github.com/nebula-contrib/ngbatis/commit/31cac59371b535e5f339b7743d03b4b4cb16991c)

This makes a lot more sense :) I saw this after replying to that :-P, thanks to the amazing @CorvusYe as always!

**Pull request merged**
