### PR TITLE
fix: style check

### PR DESCRIPTION
**Pull request by CorvusYe**

### CODE REVIEW

**Review by wey-gu — APPROVED** [review]

**Comment by CorvusYe** [comment]
!!!

https://s01.oss.sonatype.org/content/repositories/releases/org/nebula-contrib/ngbatis/1.2.0/

**Comment by wey-gu** [comment]
OMG, but why?

**Comment by CorvusYe** [comment]
I guess ... It is possible that another command also made an error in the style check step, but did not provide a clear prompt.
(style check is not required for snapshots)

I remember doing a checkstyle during the merge before, but now it seems like this step was skipped.

**Comment by wey-gu** [comment]
> (style check is not required for snapshots)

ha, golden troubleshoot mind model 👍

**Pull request merged**
