### PR TITLE
chore: modify the 'release' workflow to include Javadoc

### PR DESCRIPTION
**Pull request by CorvusYe**
as title

### CODE REVIEW

**Review by Nicole00 — APPROVED** [review]

**Comment by CorvusYe** [comment]
After this change, 'release' action failed again, and I still don't know what the problem is.

**Comment by Nicole00** [comment]
> After this change, 'release' action failed again, and I still don't know what the problem is.

the deploy lacks of asc files, the signed files with GPG.

I see you configed OSSRH_USER and OSSRH_PASSWORD and GPG_PASSWORD in the release.yml.  looks like you missied GPG username?  

you can try this action:

      - name: Deploy Release to Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}

**Comment by wey-gu** [comment]
Let's see how it goes now via https://github.com/nebula-contrib/ngbatis/pull/258 @CorvusYe @Nicole00

**Comment by CorvusYe** [comment]
I recreated a release to make the changes work, but it failed. The same configuration snapshot and v1.1.5 can be successful, not because the version is beta end, right?
@wey-gu @Nicole00

**Pull request merged**
