### PR TITLE
add EXECUTION-PROCESS.md to docs

### PR DESCRIPTION
**Pull request by syedzubeen**
Issue Link: #226 

Added the translated content of EXECUTION-PROCESS.md to operation-sequence.md

### CODE REVIEW

**Review by wey-gu — APPROVED** [review]
THANKS!

**Comment by wey-gu** [comment]
@syedzubeen could you please help fix the markdown linting failure?

**Comment by syedzubeen** [comment]
The latest commit should fix the linter issues. 😃

**Review by CorvusYe — APPROVED** [review]

**Review by CorvusYe — APPROVED** [review]

**Comment by wey-gu** [comment]
Thanks a lot for the great contribution! Cheers!

**Pull request merged**
