### PR TITLE
Draft: Upgrade to jdk 17 and SpringBoot 3.x

### LINKED ISSUE #216: Upgrading to SpringBoot 3.x
Is there any plan to  upgrade to SpringBoot `>3.x` ? There are major changes which affect this project and unfortunately make it only usable by the `2.7` version. Mainly the [changes ](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes) related to Java EE.

> Spring Boot 3.0 has migrated from Java EE to Jakarta EE APIs for all dependencies.

### PR DESCRIPTION
**Pull request by omar-araboghli**
Closes #216

I tried to cover as much as possible but there are still missing things. Maybe you guys could help. 

* I couldn't run the tests in `/ngbatis-demo` due to a `org.nebula.contrib.ngbatis.exception.QueryException`. Is there a certain config I should do when setting up the project ?
* `BeetlTextRenderTest.test2()` is failing with following exception. Any help with that from your side ? I unfortunately couldn't know where that is originating from.

```java
java.lang.reflect.InaccessibleObjectException: Unable to make public java.lang.Object java.util.Arrays$ArrayList.get(int) accessible: module java.base does not "opens java.util" to unnamed module @50b494a6
```

### CODE REVIEW

**Comment by 1244453393** [comment]
> I tried to cover as much as possible but there are still missing things. Maybe you guys could help.
> 
> * I couldn't run the tests in `/ngbatis-demo` due to a `org.nebula.contrib.ngbatis.exception.QueryException`. Is there a certain config I should do when setting up the project ?
> * `BeetlTextRenderTest.test2()` is failing with following exception. Any help with that from your side ? I unfortunately couldn't know where that is originating from.
> 
> ```java
> java.lang.reflect.InaccessibleObjectException: Unable to make public java.lang.Object java.util.Arrays$ArrayList.get(int) accessible: module java.base does not "opens java.util" to unnamed module @50b494a6
> ```

springboot2.x is still supported?

**Comment by omar-araboghli** [comment]
@1244453393, I never tested this but I don't think it's possible. At least without having additional considerations.

**Comment by 1244453393** [comment]
> @1244453393, I never tested this but I don't think it's possible. At least without having additional considerations. 

people who use the springboot2.x are still the majority

**Comment by omar-araboghli** [comment]
> people who use the springboot2.x are still the majority

What about maintaining two different releases ? It adds more efforts obviously but how would you else go with this issue internally ?

**Comment by omar-araboghli** [comment]
> people who use the springboot2.x are still the majority

What about maintaining two different releases ? It adds more efforts obviously but how would you else go with this issue internally ?

**Comment by 1244453393** [comment]
> > people who use the springboot2.x are still the majority
> 
> What about maintaining two different releases ? It adds more efforts obviously but how would you else go with this issue internally ?

there is currently no great solution,but the version transition is not very fast,this gives us ample time to study how to upgrade to the new version!XD

**Comment by CorvusYe** [comment]
My idea is that a new branch can be created.  I'll probably have some time to try on springboot3.x this Wednesday, and then I'll take a look at the problems.

**Comment by CorvusYe** [comment]
@omar-araboghli 
I may have found the root cause of the problem.

Run the following code, and the results differ between java8 and java17.
[This place](https://gitee.com/xiandafu/beetl/blob/master/beetl-core/src/main/java/org/beetl/core/fun/ObjectUtil.java#L324.) triggered this equivalent code.
Should the difference be in the handling of access permissions for private static internal classes in JDK?
```java
Class.forName("java.util.Arrays$ArrayList").getMethod("get", int.class).setAccessible(true);
```

**Review by CorvusYe — COMMENTED** [review]
@omar-araboghli 
I tried to work basically on Springboot3.x, with the exception of some of the original Array.asList test cases. Another use case that reads mapping relationships from PathWrapper is still misreporting, which is a functional flaw.

QueryException may be caused by the fact that the database does not have a schema that matches the test case.

At present, in addition to some conflicts, this PR has some codestyle problems to be solved.

It's possible to work properly. Thank you for your time.

I suggest creating another branch to be compatible with springboot3.x with a higher version number.

cc:@wey-gu

**Pull request merged**
