### PR TITLE
Formatting for lint, phase 0

### PR DESCRIPTION
**Pull request by wey-gu**
I tried best to fix all I could change.

Now in ngbatis project, it's 834 lint errors only.

The next step is to modify javadoc/coding/design and the left other failures as below.

Let's merge this ASAP because rebase is killing me o(╥﹏╥)o(just did one as I used to work on an older master)

```bash
❯ mvn checkstyle:check | grep -v "javadoc\|coding\|design"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ---------------------< org.nebula-contrib:ngbatis >---------------------
[INFO] Building ngbatis 1.1.0-beta
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-checkstyle-plugin:3.2.0:check (default-cli) @ ngbatis ---
[INFO] There are 839 errors reported by Checkstyle 9.3 with sun_checks.xml ruleset.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/Env.java:[56,10] (sizes) ParameterNumber: More than 7 parameters (found 12).
[ERROR] src/main/java/org/nebula/contrib/ngbatis/binding/DefaultArgsResolver.java:[9,39] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - com.alibaba.fastjson.serializer.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/binding/DefaultArgsResolver.java:[11,25] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - com.vesoft.nebula.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/binding/DefaultArgsResolver.java:[17,17] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - java.util.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/handler/ObjectResultHandler.java:[45,9] (misc) FinalParameters: Parameter newResult should be final.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/handler/ObjectResultHandler.java:[59,25] (misc) FinalParameters: Parameter newResult should be final.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/handler/ObjectResultHandler.java:[84,22] (misc) FinalParameters: Parameter newResult should be final.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/handler/ObjectResultHandler.java:[97,7] (misc) FinalParameters: Parameter newResult should be final.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/handler/CollectionObjectResultHandler.java:[7,17] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - java.util.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/handler/CollectionMapResultHandler.java:[8,17] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - java.util.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/handler/AbstractResultHandler.java:[11,17] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - java.util.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java:[20,23] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.jsoup.nodes.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/utils/KeySymbolMap.java:[8,17] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - java.util.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java:[10,17] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - java.util.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java:[47,40] (misc) FinalParameters: Parameter value should be final.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java:[9,43] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - com.vesoft.nebula.client.graph.data.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java:[12,17] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - java.util.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java:[12,17] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - java.util.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java:[6,65] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.nebula.contrib.ngbatis.proxy.NebulaDaoBasicExt.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/config/EnvConfig.java:[6,34] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.nebula.contrib.ngbatis.*.
[ERROR] src/main/java/org/nebula/contrib/ngbatis/NgbatisContextInitializer.java:[7,65] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.nebula.contrib.ngbatis.proxy.NebulaDaoBasicExt.*.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.685 s
[INFO] Finished at: 2022-08-26T10:34:56Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:check (default-cli) on project ngbatis: You have 839 Checkstyle violations. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

partially_implement: #22

### CODE REVIEW

**Comment by wey-gu** [comment]
After this is merged, we could do an M^ to LF change over all repo.

**Comment by CorvusYe** [comment]
@wey-gu
Sorry, I made a mistake... 
This PR may be reverted.

**Comment by CorvusYe** [comment]
I got to know it. `checkstyle.xml` and `codestyle.xml` appears in pairs.
Could you ask your colleagues if they have `codestyle.xml`.

**Comment by wey-gu** [comment]
> I got to know it. `checkstyle.xml` and `codestyle.xml` appears in pairs.
> 
> Could you ask your colleagues if they have `codestyle.xml`.
> 
> 

Ping @Nicole00

**Comment by Nicole00** [comment]
Sorry we don't have `codestyle.xml`. But you can set the `checkstyle.xml` into IDEA's `Tool->Checkstyle`

**Pull request merged**
